Ensure whitespaces in hyperref text are respected in journal PDF
NASA-IMPACT/nasa-apt pull request #492
Opened 2022-04-11 19:44 UTC by leothomas

Addresses #490:

- Hyperref in Journal PDF now respects whitespace: 
<img width="916" alt="image" src="https://user-images.githubusercontent.com/11858457/162817321-03d8e40c-0682-48fd-8774-197f5a65434e.png">

2022-04-11 20:30 UTC, leothomas commented
@danielfdsilva I tried messing around with link breaking - it's actually quite a complex subject because the compiler has to make an intelligent decision about where to break the text, _before_ the text get's into the margin. So for example: 
```
https://www.developmentseed.org?team=earthdata
                                                                               ^margin
```
If only the word `earthdata` extends into the margin, LaTeX _should_ break the url at the `=` char, however, when the compiler processes the document and gets to the `=` character, it _isn't yet in the margin_ so it doesn't think to insert a linebreak. 

It's a classic example of something that is visually so easy, but complex programatically (similar to table column width for example).

I'm going to table this issue for now, since we haven't had any user feedback on excessively long URLs

2022-04-12 08:50 UTC, danielfdsilva requested changes

2022-04-12 08:50 UTC, danielfdsilva commented on app/pdf/generator.py
> +            print("HYPERLINK: ", hyperlink(d["url"], d["children"][0]["text"]))
debug print?

2022-04-12 12:46 UTC, leothomas commented on app/pdf/generator.py
> +            print("HYPERLINK: ", hyperlink(d["url"], d["children"][0]["text"]))
Indeed!

2022-04-13 18:53 UTC, merged